export { cli } from './cli.js';
export {
  compareImages,
  type CompareImagesOptions,
  type CompareImagesReport,
  type CompareRegionScore,
  type CompareVerdict,
} from './compare.js';
export {
  buildFlowchartSpec,
  buildCodeSpec,
  buildTerminalSpec,
  buildCardsSpec,
} from './templates/index.js';
export {
  DEFAULT_GENERATOR_VERSION,
  computeSpecHash,
  inferSidecarPath,
  renderDesign,
  writeRenderArtifacts,
  type LayoutSnapshot,
  type Rect,
  type RenderMetadata,
  type RenderResult,
  type RenderedElement,
  type WrittenArtifacts,
} from './renderer.js';
export type { EdgeRoute, ElkLayoutResult, LayoutResult } from './layout/index.js';
export { renderDrawCommands } from './renderers/draw.js';
export {
  arcRoute,
  bezierPointAt,
  computeDiagramCenter,
  curveRoute,
  edgeAnchor,
  orthogonalRoute,
  outwardNormal,
  rectCenter,
  renderConnection,
  type ConnectionArrow,
  type ConnectionRenderOptions,
  type ConnectionRouting,
  type ConnectionStrokeStyle,
  type CubicBezierSegment,
  type Point,
} from './renderers/connection.js';
export {
  readMetadata,
  runQa,
  type QaIssue,
  type QaReferenceResult,
  type QaReport,
  type QaSeverity,
} from './qa.js';
export { loadFonts } from './fonts.js';
export {
  builtInThemeBackgrounds,
  builtInThemes,
  connectionElementSchema,
  defaultAutoLayout,
  defaultCanvas,
  defaultConstraints,
  defaultGridLayout,
  defaultLayout,
  defaultStackLayout,
  defaultTheme,
  deriveSafeFrame,
  designSpecSchema,
  diagramElementSchema,
  diagramLayoutSchema,
  diagramSpecSchema,
  flowNodeElementSchema,
  inferLayout,
  parseDesignSpec,
  parseDiagramSpec,
  resolveTheme,
  type AutoLayoutConfig,
  type BuiltInTheme,
  type CardElement,
  type CodeBlockElement,
  type ConnectionElement,
  type ConstraintSpec,
  type Decorator,
  type DesignCardSpec,
  type DesignSafeFrame,
  type DesignSpec,
  type DesignTheme,
  type DiagramElement,
  type DiagramLayout,
  type DiagramSpec,
  type DrawBadge,
  type DrawBezier,
  type DrawCircle,
  type DrawCommand,
  type DrawFontFamily,
  type DrawGradientRect,
  type DrawLine,
  type DrawPath,
  type DrawPoint,
  type DrawRect,
  type DrawText,
  type Element,
  type FlowNodeElement,
  type Gradient,
  type GradientOverlayDecorator,
  type GridLayoutConfig,
  type ImageElement,
  type LayoutConfig,
  type ManualLayoutConfig,
  type RainbowRuleDecorator,
  type ShapeElement,
  type StackLayoutConfig,
  type TerminalElement,
  type TextElement,
  type Theme,
  type ThemeInput,
  type VignetteDecorator,
} from './spec.schema.js';
export {
  DEFAULT_RAINBOW_COLORS,
  drawGradientRect,
  drawRainbowRule,
  drawVignette,
  type GradientSpec,
  type GradientStop,
} from './primitives/gradients.js';
export { resolveShikiTheme, themeToShikiMap } from './themes/index.js';
export {
  disposeHighlighter,
  highlightCode,
  initHighlighter,
  type HighlightedLine,
} from './syntax/highlighter.js';
export * from './publish/index.js';
