import { z } from 'incur';
import {
  type DesignSpec,
  defaultCanvas,
  defaultConstraints,
  defaultLayout,
  defaultTheme,
  parseDesignSpec,
} from '../spec.schema.js';

export const templateBaseSchema = z
  .object({
    eyebrow: z.string().min(1).max(64).optional(),
    title: z.string().min(1).max(120),
    subtitle: z.string().min(1).max(240).optional(),
    footer: z.string().min(1).max(200).optional(),
    tagline: z.string().min(1).max(140).optional(),
  })
  .strict();

export function buildBaseSpec(input: {
  template: DesignSpec['template'];
  title: string;
  subtitle?: string;
  eyebrow?: string;
  footer?: string;
  tagline?: string;
  cards: DesignSpec['cards'];
  templateVersion: string;
  columns?: number;
}): DesignSpec {
  return parseDesignSpec({
    version: 1,
    template: input.template,
    canvas: defaultCanvas,
    theme: defaultTheme,
    header: {
      eyebrow: input.eyebrow ?? 'SPECTRA GTM',
      title: input.title,
      subtitle: input.subtitle,
    },
    cards: input.cards,
    footer: {
      text: input.footer ?? 'Generated by @spectratools/graphic-designer',
      tagline: input.tagline,
    },
    layout: {
      ...defaultLayout,
      columns: input.columns ?? defaultLayout.columns,
    },
    constraints: defaultConstraints,
    generation: {
      templateVersion: input.templateVersion,
    },
  });
}
