import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { cli } from '../cli.js';

type CliResult = {
  output: string;
  exitCode: number;
};

async function runCli(argv: string[]): Promise<CliResult> {
  let output = '';
  let exitCode = 0;

  await cli.serve(argv, {
    stdout: (chunk) => {
      output += chunk;
    },
    exit: (code) => {
      exitCode = code;
    },
  });

  return { output, exitCode };
}

describe('design render cli', () => {
  it('accepts iteration flags and returns structured iteration output metadata', async () => {
    const tmp = await mkdtemp(join(tmpdir(), 'graphic-designer-cli-render-iteration-'));
    const specPath = join(tmp, 'spec.json');
    const outDir = join(tmp, 'out');

    await writeFile(
      specPath,
      JSON.stringify(
        {
          version: 2,
          canvas: { width: 1200, height: 675, padding: 48 },
          theme: 'dark',
          header: {
            title: 'Iteration Metadata',
            subtitle: 'Render command metadata coverage',
          },
          elements: [{ type: 'card', id: 'card1', title: 'A', body: 'B' }],
          footer: { text: 'Generated by tests' },
          layout: { mode: 'grid', columns: 1, gap: 24, equalHeight: true },
        },
        null,
        2,
      ),
      'utf8',
    );

    const result = await runCli([
      'render',
      '--spec',
      specPath,
      '--out',
      outDir,
      '--iteration',
      '2',
      '--max-iterations',
      '3',
      '--iteration-notes',
      'Adjusted color contrast',
      '--previous-hash',
      'prev-hash-001',
      '--json',
    ]);

    expect(result.exitCode).toBe(0);

    const payload = JSON.parse(result.output) as {
      iteration?: { current: number; max: number; isLast: boolean; notes?: string };
      metadataPath: string;
      qa: { pass: boolean };
    };

    expect(payload.qa.pass).toBe(true);
    expect(payload.iteration).toEqual({
      current: 2,
      max: 3,
      isLast: false,
      notes: 'Adjusted color contrast',
    });

    const metadataRaw = await readFile(payload.metadataPath, 'utf8');
    const metadata = JSON.parse(metadataRaw) as {
      iteration?: {
        iteration: number;
        maxIterations?: number;
        notes?: string;
        previousHash?: string;
      };
    };

    expect(metadata.iteration).toEqual({
      iteration: 2,
      maxIterations: 3,
      notes: 'Adjusted color contrast',
      previousHash: 'prev-hash-001',
    });
  });

  it('rejects dependent iteration flags when --iteration is omitted', async () => {
    const tmp = await mkdtemp(join(tmpdir(), 'graphic-designer-cli-render-iteration-invalid-'));
    const specPath = join(tmp, 'spec.json');
    const outDir = join(tmp, 'out');

    await writeFile(
      specPath,
      JSON.stringify({
        version: 2,
        theme: 'dark',
        elements: [{ type: 'card', id: 'card1', title: 'A', body: 'B' }],
      }),
      'utf8',
    );

    const result = await runCli([
      'render',
      '--spec',
      specPath,
      '--out',
      outDir,
      '--max-iterations',
      '3',
      '--json',
    ]);

    expect(result.exitCode).toBe(1);
    expect(result.output).toContain('INVALID_ITERATION_OPTIONS');
  });
});
