import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { cli } from '../cli.js';

type CliResult = {
  output: string;
  exitCode: number;
};

async function runCli(argv: string[]): Promise<CliResult> {
  let output = '';
  let exitCode = 0;

  await cli.serve(argv, {
    stdout: (chunk) => {
      output += chunk;
    },
    exit: (code) => {
      exitCode = code;
    },
  });

  return { output, exitCode };
}

const minimalSpec = {
  version: 2,
  canvas: { width: 1200, height: 675, padding: 48 },
  theme: 'dark',
  header: { title: 'Draw Alias Test', subtitle: 'Compatibility alias' },
  elements: [{ type: 'card', id: 'card1', title: 'Hello', body: 'World' }],
  footer: { text: 'Generated by tests' },
  layout: { mode: 'grid', columns: 1, gap: 24, equalHeight: true },
};

describe('draw command alias', () => {
  it('renders a spec via the draw command with positional arg and --output', async () => {
    const tmp = await mkdtemp(join(tmpdir(), 'graphic-designer-cli-draw-alias-'));
    const specPath = join(tmp, 'spec.json');
    const outDir = join(tmp, 'out');

    await writeFile(specPath, JSON.stringify(minimalSpec, null, 2), 'utf8');

    const result = await runCli(['draw', specPath, '--output', outDir, '--json']);

    expect(result.exitCode).toBe(0);

    const payload = JSON.parse(result.output) as {
      imagePath: string;
      qa: { pass: boolean };
    };

    expect(payload.qa.pass).toBe(true);
    expect(payload.imagePath).toContain(outDir);
  });

  it('renders a spec via the draw command with --out flag', async () => {
    const tmp = await mkdtemp(join(tmpdir(), 'graphic-designer-cli-draw-out-'));
    const specPath = join(tmp, 'spec.json');
    const outDir = join(tmp, 'out');

    await writeFile(specPath, JSON.stringify(minimalSpec, null, 2), 'utf8');

    const result = await runCli(['draw', specPath, '--out', outDir, '--json']);

    expect(result.exitCode).toBe(0);

    const payload = JSON.parse(result.output) as {
      imagePath: string;
      qa: { pass: boolean };
    };

    expect(payload.qa.pass).toBe(true);
    expect(payload.imagePath).toContain(outDir);
  });

  it('fails when neither --out nor --output is provided', async () => {
    const tmp = await mkdtemp(join(tmpdir(), 'graphic-designer-cli-draw-noout-'));
    const specPath = join(tmp, 'spec.json');

    await writeFile(specPath, JSON.stringify(minimalSpec, null, 2), 'utf8');

    const result = await runCli(['draw', specPath, '--json']);

    expect(result.exitCode).toBe(1);
    expect(result.output).toContain('MISSING_OUTPUT');
  });
});

describe('render --output alias', () => {
  it('accepts --output as an alias for --out on the render command', async () => {
    const tmp = await mkdtemp(join(tmpdir(), 'graphic-designer-cli-render-output-alias-'));
    const specPath = join(tmp, 'spec.json');
    const outDir = join(tmp, 'out');

    await writeFile(specPath, JSON.stringify(minimalSpec, null, 2), 'utf8');

    const result = await runCli(['render', '--spec', specPath, '--output', outDir, '--json']);

    expect(result.exitCode).toBe(0);

    const payload = JSON.parse(result.output) as {
      imagePath: string;
      qa: { pass: boolean };
    };

    expect(payload.qa.pass).toBe(true);
    expect(payload.imagePath).toContain(outDir);
  });

  it('prefers --out over --output when both are provided', async () => {
    const tmp = await mkdtemp(join(tmpdir(), 'graphic-designer-cli-render-both-'));
    const specPath = join(tmp, 'spec.json');
    const outDir = join(tmp, 'out-primary');
    const outputDir = join(tmp, 'out-alias');

    await writeFile(specPath, JSON.stringify(minimalSpec, null, 2), 'utf8');

    const result = await runCli([
      'render',
      '--spec',
      specPath,
      '--out',
      outDir,
      '--output',
      outputDir,
      '--json',
    ]);

    expect(result.exitCode).toBe(0);

    const payload = JSON.parse(result.output) as {
      imagePath: string;
      qa: { pass: boolean };
    };

    expect(payload.qa.pass).toBe(true);
    expect(payload.imagePath).toContain(outDir);
  });
});
