import { mkdtemp, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { runQa } from '../qa.js';
import { renderDesign, writeRenderArtifacts } from '../renderer.js';
import { parseDesignSpec } from '../spec.schema.js';
import { resolveTheme } from '../themes/index.js';

function buildQaSpec() {
  return parseDesignSpec({
    version: 2,
    canvas: { width: 1200, height: 675, padding: 48 },
    theme: 'dark',
    header: { title: 'QA Spec' },
    elements: [
      { type: 'card', id: 'one', title: 'One', body: 'steady growth', metric: '90%' },
      { type: 'card', id: 'two', title: 'Two', body: 'strong channel mix', metric: '4.4%' },
      { type: 'card', id: 'three', title: 'Three', body: 'cost improving', metric: '$10' },
    ],
    footer: { text: 'Generated by tests' },
    layout: { mode: 'grid', columns: 3, gap: 24, equalHeight: true },
    constraints: {
      minContrastRatio: 4.5,
      minFooterSpacing: 16,
      checkOverlaps: true,
      maxTextTruncation: 0.1,
    },
  });
}

describe('qa gate', () => {
  it('passes for a valid rendered artifact', async () => {
    const spec = buildQaSpec();

    const render = await renderDesign(spec, { generatorVersion: 'test-qa' });
    const dir = await mkdtemp(join(tmpdir(), 'graphic-designer-qa-pass-'));
    const written = await writeRenderArtifacts(render, dir);

    const report = await runQa({
      imagePath: written.imagePath,
      spec,
      metadata: written.metadata,
    });

    expect(report.pass).toBe(true);
    expect(report.issues).toHaveLength(0);
  });

  it('fails when contrast rules are violated', async () => {
    const base = buildQaSpec();
    const theme = resolveTheme(base.theme);

    const spec = parseDesignSpec({
      ...base,
      theme: {
        ...theme,
        text: theme.surface,
        textMuted: theme.surface,
      },
    });

    const render = await renderDesign(spec, { generatorVersion: 'test-qa' });
    const dir = await mkdtemp(join(tmpdir(), 'graphic-designer-qa-fail-'));
    const imagePath = join(dir, 'out.png');
    const metaPath = join(dir, 'out.meta.json');

    await writeFile(imagePath, render.png);
    await writeFile(metaPath, JSON.stringify(render.metadata, null, 2));

    const report = await runQa({
      imagePath,
      spec,
      metadata: render.metadata,
    });

    expect(report.pass).toBe(false);
    expect(report.issues.some((issue) => issue.code === 'LOW_CONTRAST')).toBe(true);
  });
});
