import { mkdtemp, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import sharp from 'sharp';
import { describe, expect, it } from 'vitest';
import { renderDesign, writeRenderArtifacts } from '../renderer.js';
import { parseDesignSpec } from '../spec.schema.js';

function makeCardSpec() {
  return parseDesignSpec({
    version: 2,
    canvas: { width: 1200, height: 675, padding: 48 },
    theme: 'dark',
    header: {
      title: 'Determinism Test',
      subtitle: 'Same input should produce same hash',
    },
    elements: [
      {
        type: 'card',
        id: 'ingest',
        title: 'Ingest',
        body: 'Collect target signals',
        badge: 'step 1',
        metric: '120 leads',
      },
      {
        type: 'card',
        id: 'score',
        title: 'Score',
        body: 'Prioritize opportunities',
        badge: 'step 2',
        metric: '42 SQOs',
      },
      {
        type: 'card',
        id: 'ship',
        title: 'Ship',
        body: 'Deliver launch kits',
        badge: 'step 3',
        metric: '9 campaigns',
        tone: 'success',
      },
    ],
    footer: {
      text: 'Generated by @spectratools/graphic-designer-cli',
    },
    layout: {
      mode: 'grid',
      columns: 3,
      gap: 24,
      equalHeight: true,
    },
    constraints: {
      minContrastRatio: 4.5,
      minFooterSpacing: 16,
      checkOverlaps: true,
      maxTextTruncation: 0.1,
    },
  });
}

describe('renderer', () => {
  it('is deterministic for same spec + generator version', async () => {
    const spec = makeCardSpec();

    const first = await renderDesign(spec, {
      generatorVersion: 'test-1.0.0',
      renderedAt: '2026-03-09T00:00:00.000Z',
    });
    const second = await renderDesign(spec, {
      generatorVersion: 'test-1.0.0',
      renderedAt: '2026-03-09T00:00:01.000Z',
    });

    expect(first.metadata.specHash).toBe(second.metadata.specHash);
    expect(first.metadata.artifactHash).toBe(second.metadata.artifactHash);
    expect(first.metadata.iteration).toBeUndefined();
    expect(second.metadata.iteration).toBeUndefined();
    expect(first.png.equals(second.png)).toBe(true);
  });

  it('records iteration metadata when provided', async () => {
    const spec = makeCardSpec();

    const rendered = await renderDesign(spec, {
      generatorVersion: 'test-1.0.0',
      iteration: {
        iteration: 2,
        maxIterations: 4,
        notes: 'Adjusted contrast and spacing.',
        previousHash: 'abc123previoushash',
      },
    });

    expect(rendered.metadata.iteration).toEqual({
      iteration: 2,
      maxIterations: 4,
      notes: 'Adjusted contrast and spacing.',
      previousHash: 'abc123previoushash',
    });
  });

  it('writes image and metadata sidecar with deterministic naming strategy', async () => {
    const spec = makeCardSpec();
    const render = await renderDesign(spec, { generatorVersion: 'test-1.0.0' });
    const dir = await mkdtemp(join(tmpdir(), 'graphic-designer-'));
    const written = await writeRenderArtifacts(render, dir);

    const metaRaw = await readFile(written.metadataPath, 'utf8');
    const parsed = JSON.parse(metaRaw) as { artifactHash: string; artifactBaseName: string };

    expect(written.imagePath).toContain(`${render.metadata.artifactBaseName}.png`);
    expect(parsed.artifactHash).toBe(render.metadata.artifactHash);
    expect(parsed.artifactBaseName).toBe(render.metadata.artifactBaseName);
  });

  it('dispatches all element renderers in a single spec', async () => {
    const spec = parseDesignSpec({
      version: 2,
      theme: 'dark',
      header: { title: 'Dispatch test' },
      footer: { text: 'footer' },
      layout: {
        mode: 'manual',
        positions: {
          card1: { x: 48, y: 120, width: 240, height: 180 },
          fn1: { x: 360, y: 140, width: 190, height: 120 },
          fn2: { x: 660, y: 140, width: 190, height: 120 },
          term1: { x: 48, y: 330, width: 340, height: 220 },
          code1: { x: 410, y: 330, width: 360, height: 220 },
          txt1: { x: 790, y: 330, width: 320, height: 120 },
          shp1: { x: 820, y: 470, width: 220, height: 80 },
          img1: { x: 48, y: 570, width: 280, height: 80 },
        },
      },
      elements: [
        { type: 'card', id: 'card1', title: 'Card', body: 'Body' },
        { type: 'flow-node', id: 'fn1', shape: 'rounded-box', label: 'Start' },
        { type: 'flow-node', id: 'fn2', shape: 'diamond', label: 'Decision', sublabel: 'yes/no' },
        {
          type: 'connection',
          from: 'fn1',
          to: 'fn2',
          style: 'dashed',
          arrow: 'end',
          label: 'path',
        },
        {
          type: 'terminal',
          id: 'term1',
          content: 'echo hello\nls -la',
          title: 'Terminal',
          style: { windowControls: 'macos', scale: 1 },
        },
        {
          type: 'code-block',
          id: 'code1',
          language: 'ts',
          code: 'const x = 1;\nconsole.log(x);',
          showLineNumbers: true,
          startLine: 1,
          title: 'Code',
          style: { scale: 1 },
        },
        {
          type: 'text',
          id: 'txt1',
          content: 'Hello renderer dispatch',
          style: 'subheading',
          align: 'left',
        },
        {
          type: 'shape',
          id: 'shp1',
          shape: 'arrow',
          fill: '#1A2547',
          stroke: '#7AA2FF',
          strokeWidth: 2,
        },
        {
          type: 'image',
          id: 'img1',
          src: 'file:///definitely-missing.png',
          alt: 'placeholder image',
        },
      ],
    });

    const rendered = await renderDesign(spec, { generatorVersion: 'test-dispatch' });

    expect(rendered.metadata.layout.elements.some((el) => el.id === 'card-card1')).toBe(true);
    expect(rendered.metadata.layout.elements.some((el) => el.id === 'flow-node-fn1')).toBe(true);
    expect(rendered.metadata.layout.elements.some((el) => el.kind === 'connection')).toBe(true);
    expect(rendered.metadata.layout.elements.some((el) => el.id === 'terminal-term1')).toBe(true);
    expect(rendered.metadata.layout.elements.some((el) => el.id === 'code-code1')).toBe(true);
    expect(rendered.metadata.layout.elements.some((el) => el.id === 'text-txt1')).toBe(true);
    expect(rendered.metadata.layout.elements.some((el) => el.id === 'shape-shp1')).toBe(true);
    expect(rendered.metadata.layout.elements.some((el) => el.id === 'image-img1')).toBe(true);
  });

  it('renders solid and gradient backgrounds', async () => {
    const solidSpec = parseDesignSpec({
      canvas: { width: 640, height: 360, padding: 32 },
      theme: 'dark',
      background: '#112233',
      elements: [{ type: 'card', id: 'a', title: 'A', body: 'B' }],
    });

    const gradientSpec = parseDesignSpec({
      canvas: { width: 640, height: 360, padding: 32 },
      theme: 'dark',
      background: {
        type: 'linear',
        angle: 180,
        stops: [
          { offset: 0, color: '#000000' },
          { offset: 1, color: '#FFFFFF' },
        ],
      },
      elements: [{ type: 'card', id: 'b', title: 'B', body: 'C' }],
    });

    const solid = await renderDesign(solidSpec, { generatorVersion: 'test-background-solid' });
    const gradient = await renderDesign(gradientSpec, {
      generatorVersion: 'test-background-gradient',
    });

    const solidRaw = await sharp(solid.png)
      .ensureAlpha()
      .raw()
      .toBuffer({ resolveWithObject: true });
    const gradientRaw = await sharp(gradient.png)
      .ensureAlpha()
      .raw()
      .toBuffer({ resolveWithObject: true });

    const solidTopLeft = solidRaw.data[0] + solidRaw.data[1] + solidRaw.data[2];
    const gradientTop = gradientRaw.data[0] + gradientRaw.data[1] + gradientRaw.data[2];
    const bottomIndex =
      gradientRaw.info.width * (gradientRaw.info.height - 1) * gradientRaw.info.channels;
    const gradientBottom =
      gradientRaw.data[bottomIndex] +
      gradientRaw.data[bottomIndex + 1] +
      gradientRaw.data[bottomIndex + 2];

    expect(solidTopLeft).toBeLessThan(120);
    expect(gradientBottom).toBeGreaterThan(gradientTop);
  });

  it('processes decorators and renders vignette as the final overlay step', async () => {
    const spec = parseDesignSpec({
      canvas: { width: 960, height: 540, padding: 48 },
      theme: 'dark',
      header: { title: 'Decorators' },
      footer: { text: 'footer' },
      layout: {
        mode: 'manual',
        positions: {
          card1: { x: 80, y: 180, width: 320, height: 180 },
        },
      },
      decorators: [
        {
          type: 'gradient-overlay',
          opacity: 0.25,
          gradient: {
            type: 'radial',
            stops: [
              { offset: 0, color: '#FFFFFF' },
              { offset: 1, color: '#000000' },
            ],
          },
        },
        { type: 'rainbow-rule', y: 'after-header', thickness: 4, margin: 24 },
        { type: 'vignette', intensity: 0.4, color: '#000000' },
      ],
      elements: [{ type: 'card', id: 'card1', title: 'A', body: 'B' }],
    });

    const rendered = await renderDesign(spec, { generatorVersion: 'test-decorators' });

    const ids = rendered.metadata.layout.elements.map((element) => element.id);
    const gradientOverlayIndex = ids.indexOf('decorator-gradient-overlay-0');
    const rainbowRuleIndex = ids.indexOf('decorator-rainbow-rule-1');
    const vignetteIndex = ids.indexOf('decorator-vignette-2');
    const cardIndex = ids.findIndex((id) => id.startsWith('card-card1'));

    expect(gradientOverlayIndex).toBeGreaterThanOrEqual(0);
    expect(rainbowRuleIndex).toBeGreaterThanOrEqual(0);
    expect(vignetteIndex).toBeGreaterThanOrEqual(0);
    expect(cardIndex).toBeGreaterThanOrEqual(0);
    expect(gradientOverlayIndex).toBeLessThan(cardIndex);
    expect(rainbowRuleIndex).toBeLessThan(cardIndex);
    expect(vignetteIndex).toBeGreaterThan(cardIndex);

    const decoratorElements = rendered.metadata.layout.elements.filter((element) =>
      element.id.startsWith('decorator-'),
    );
    expect(decoratorElements.every((element) => element.allowOverlap)).toBe(true);
  });

  it('renders flow elements with auto layout using ELK', async () => {
    const spec = parseDesignSpec({
      elements: [
        { type: 'flow-node', id: 'n1', shape: 'box', label: 'Node A' },
        { type: 'flow-node', id: 'n2', shape: 'diamond', label: 'Node B' },
        { type: 'connection', from: 'n1', to: 'n2' },
      ],
    });

    const rendered = await renderDesign(spec, { generatorVersion: 'test-auto-layout' });

    expect(rendered.metadata.layout.elements.some((el) => el.id === 'flow-node-n1')).toBe(true);
    expect(rendered.metadata.layout.elements.some((el) => el.id === 'flow-node-n2')).toBe(true);
    expect(rendered.metadata.layout.elements.some((el) => el.kind === 'connection')).toBe(true);
  });
});
